### ISSUE TITLE
Add more view

### ISSUE THREAD

**Issue by mabed-fr** [iEvgeny/cctv-viewer#86]
Hello,

I have only two cam and i use 2x2 cam but i have too many windows, a "1+1" view or 2x1 is it possible ?

**Comment by iEvgeny** [comment]
Hi!
You have two tools at your disposal to configure the viewport grid:

1. Window division (Press and hold the left mouse button on any Division button to adjust the custom ratio)
2. Merging viewports (For example, select a 2x2 viewport square and click the Merging cells button)

**Comment by mabed-fr** [comment]
The method 1 works but the windows are small (see screen)

![image](https://github.com/iEvgeny/cctv-viewer/assets/25350431/256a6b93-08d6-42cc-aae5-001d37f9b5cb)


Method two doesn't work, do you have a gif or doc videos?

**Comment by iEvgeny** [comment]
I don't really understand what the problem is.
![image](https://github.com/iEvgeny/cctv-viewer/assets/3954130/5e7543ac-f3c5-4127-86b3-184f82b145c8)
![image](https://github.com/iEvgeny/cctv-viewer/assets/3954130/d6033b98-0e32-4d79-8c91-07ba53a8d7ea)

P.S.
There is a bug with not being able to expand the viewport over the black fields around the viewport grid, but I assume that's not what you mean.

**Comment by mabed-fr** [comment]
> P.S.
> There is a bug with not being able to expand the viewport over the black fields around the viewport grid, but I assume that's not what you mean.

Yes i have lot of black on the side of the image with 1x2 and 2x1 do you have any informations ?

**Comment by iEvgeny** [comment]
Just resize the CCTV Viewer window so that there are no black margins.

**Comment by mabed-fr** [comment]
I open new issue
